FROM registry.access.redhat.com/ubi9:latest as builder

COPY oneAPI.repo /etc/yum.repos.d/

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm ; \
    dnf list | grep intel ; \
    dnf install -y pciutils clinfo intel-oneapi-runtime-opencl g++ cmake git libcurl-devel intel-oneapi-base-toolkit intel-gmmlib-devel intel-igc-devel.x86_64; \
    git clone https://github.com/ggerganov/llama.cpp.git -b b4523 ; \
    cd llama.cpp ; \
    mkdir -p build ; \
    cd build ; \
    source /opt/intel/oneapi/setvars.sh ; \
    cmake .. -DGGML_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DLLAMA_CURL=ON -DGGML_CCACHE=OFF -DGGML_NATIVE=ON ; \
    cmake --build . --config Release -j -v ; \
    cmake --install . --prefix /llama-cpp ; \
    cd ; \
    git clone https://github.com/intel/compute-runtime.git -b releases/24.52 ; \
    mkdir compute-runtime/build ; \
    cd compute-runtime/build ; \
    cmake -DCMAKE_BUILD_TYPE=Release -DNEO_SKIP_UNIT_TESTS=1 ../ ; \
    make -j`nproc` ; \
    make install ; \

FROM registry.access.redhat.com/ubi9:latest

ARG PACKAGES="intel-oneapi-runtime-opencl pciutils clinfo intel-oneapi-runtime-compilers intel-oneapi-mkl-core intel-oneapi-mkl-sycl-blas intel-oneapi-runtime-dnnl"

ENV LD_LIBRARY_PATH="/usr/local/lib64:/usr/local/lib/:/opt/intel/oneapi/mkl/2025.0/lib:/opt/intel/oneapi/compiler/2025.0/opt/compiler/lib:/opt/intel/oneapi/compiler/2025.0/lib/clang/19/lib:/opt/intel/oneapi/compiler/2025.0/lib:/opt/intel/oneapi/umf/0.9/lib:/opt/intel/oneapi/tbb/2022.0/lib:/opt/intel/oneapi/tcm/1.2/lib:/opt/intel/oneapi/redist/opt/compiler/lib:/opt/intel/oneapi/redist/lib/clang/19/lib:/opt/intel/oneapi/redist/lib:/opt/intel/oneapi/mkl/2025.0/lib:/opt/intel/oneapi/compiler/2025.0/opt/compiler/lib:/opt/intel/oneapi/compiler/2025.0/lib/clang/19/lib:/opt/intel/oneapi/compiler/2025.0/lib:/opt/intel/oneapi/umf/0.9/lib:/opt/intel/oneapi/tbb/2022.0/lib:/opt/intel/oneapi/tcm/1.2/lib:/opt/intel/oneapi/redist/opt/compiler/lib:/opt/intel/oneapi/redist/lib/clang/19/lib:/opt/intel/oneapi/redist/lib"

COPY --from=builder /llama-cpp/bin/ /usr/local/bin/
COPY --from=builder /llama-cpp/lib/ /usr/local/lib/
COPY --from=builder /llama-cpp/lib64/ /usr/local/lib64/
COPY --from=builder /llama-cpp/include/ /usr/local/include/
COPY --from=builder /etc/OpenCL/vendors/intel.icd /etc/OpenCL/vendors/intel.icd
COPY --from=builder /usr/local/bin/ocloc-24.52.1 /usr/local/bin/ocloc-24.52.1
COPY --from=builder /usr/local/lib64/libocloc.so /usr/local/lib64/libocloc.so
COPY --from=builder /usr/local/include/ocloc_api.h /usr/local/include/ocloc_api.h
COPY --from=builder /usr/local/lib64/intel-opencl/libigdrcl.so /usr/local/lib64/intel-opencl/libigdrcl.so
COPY oneAPI.repo /etc/yum.repos.d/

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm ; \
    dnf install -y ${PACKAGES} ; \
    chown 0:0 /etc/passwd ; \
    chown 0:0 /etc/group ; \
    chmod g=u /etc/passwd /etc/group ; \
    useradd -u 1000 -g render -G video -s /bin/bash -d /home/llama-user llama-user

USER 1000
WORKDIR /home/llama-user

